#!/usr/bin/env python
"""Generate app/src/lib/protocol.ts from acis/protocol.py.

Run with: just gen-types

Each Pydantic model in protocol.py becomes a TypeScript interface.
The discriminated-union ``Inbound`` type is not emitted (the app only sends,
it doesn't parse inbound).  Outbound types are emitted as a union so the app
can switch on ``msg.type``.
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path
from textwrap import dedent
from typing import Literal, Union, get_args, get_origin

# Ensure src/ is importable when running from repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import acis.protocol as proto  # noqa: E402

_PY_TO_TS = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "None": "null",
    "dict": "Record<string, unknown>",
    "list": "unknown[]",
}

_OUTBOUND_MODELS = [
    proto.HelloOk,
    proto.SessionStarted,
    proto.SessionStopped,
    proto.TranscriptDelta,
    proto.CueNew,
    proto.SummaryReady,
    proto.Error,
    proto.Pong,
]

_INBOUND_MODELS = [
    proto.Hello,
    proto.SessionStart,
    proto.SessionStop,
    proto.AudioChunk,
    proto.Ping,
]


def _py_type_to_ts(annotation) -> str:
    if annotation is type(None):
        return "null"
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Literal:
        return " | ".join(f'"{a}"' if isinstance(a, str) else str(a) for a in args)
    if origin is Union or str(origin) == "typing.Union":
        parts = [_py_type_to_ts(a) for a in args]
        return " | ".join(parts)
    if origin is list or origin is List:
        return f"{_py_type_to_ts(args[0])}[]" if args else "unknown[]"
    if origin is dict:
        k = _py_type_to_ts(args[0]) if args else "string"
        v = _py_type_to_ts(args[1]) if len(args) > 1 else "unknown"
        return f"Record<{k}, {v}>"
    name = getattr(annotation, "__name__", str(annotation))
    return _PY_TO_TS.get(name, name)


def _model_to_ts(model) -> str:
    lines = [f"export interface {model.__name__} {{"]
    for fname, finfo in model.model_fields.items():
        ann = finfo.annotation
        ts_type = _py_type_to_ts(ann)
        optional = "?" if not finfo.is_required() else ""
        lines.append(f"  {fname}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    out_path = Path(__file__).resolve().parents[1] / "app" / "src" / "lib" / "protocol.ts"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    sections: list[str] = [
        "// AUTO-GENERATED by scripts/gen_ts_protocol.py — do not edit by hand.\n",
        "// ── Inbound (app → brain) ──────────────────────────────────────────────────\n",
    ]
    for model in _INBOUND_MODELS:
        sections.append(_model_to_ts(model))
    sections.append("\nexport type Inbound = " + " | ".join(m.__name__ for m in _INBOUND_MODELS) + ";\n")

    sections.append("\n// ── Outbound (brain → app) ─────────────────────────────────────────────────\n")
    for model in _OUTBOUND_MODELS:
        sections.append(_model_to_ts(model))
    sections.append("\nexport type Outbound = " + " | ".join(m.__name__ for m in _OUTBOUND_MODELS) + ";\n")

    out_path.write_text("\n".join(sections) + "\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    try:
        from typing import List
    except ImportError:
        pass
    main()
