"""Replay a fixture transcript through the live ACIS server via text injection.

Parses the [HH:MM:SS] timestamped transcript and sends each line as a
``text.line`` WS message — no mic, no TTS, no audio encoding required.
The server feeds lines directly into the utterance pipeline (cue extraction
and summary run as normal).

Usage:
    uv run python tools/replay_fixture.py tests/fixtures/tuc_startup_meeting/transcript.txt
    uv run python tools/replay_fixture.py tests/fixtures/german_startup_seminar/transcript.txt
    uv run python tools/replay_fixture.py tests/fixtures/tuc_startup_meeting/transcript.txt --url ws://192.168.204.102:8765
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re

import websockets

# ── Transcript parser ─────────────────────────────────────────────────────────

_TIMESTAMP_RE = re.compile(r"^\[[\d:]+\]$")
_HEADER_LINES = 4  # title, date, location, "Generated by AI." line


def parse_transcript(path: str) -> list[str]:
    """Return non-empty utterance lines from the fixture file."""
    lines = open(path).read().splitlines()
    utterances: list[str] = []
    for line in lines[_HEADER_LINES:]:
        line = line.strip()
        if not line or _TIMESTAMP_RE.match(line):
            continue
        utterances.append(line)
    return utterances


# ── WebSocket client ──────────────────────────────────────────────────────────

async def replay(url: str, session_name: str, lines: list[str], delay: float = 0.05) -> None:
    print(f"\nConnecting to {url}…")
    async with websockets.connect(url, ping_interval=None) as ws:
        # Handshake
        await ws.send(json.dumps({"type": "hello"}))
        msg = json.loads(await asyncio.wait_for(ws.recv(), timeout=5.0))
        assert msg["type"] == "hello.ok", msg
        print("  connected")

        # Start session
        await ws.send(json.dumps({"type": "session.start", "name": session_name}))
        msg = json.loads(await asyncio.wait_for(ws.recv(), timeout=5.0))
        assert msg["type"] == "session.started", msg
        print(f"  session started ({msg['session_id'][:8]}…)")

        # Inject text lines
        print(f"\nInjecting {len(lines)} lines (delay={delay}s)…")
        for i, line in enumerate(lines, 1):
            await ws.send(json.dumps({"type": "text.line", "text": line}))
            print(f"  [{i}/{len(lines)}] {line[:70]}", flush=True)
            if delay > 0:
                await asyncio.sleep(delay)

        # Stop session
        await ws.send(json.dumps({"type": "session.stop"}))
        print("\n  session.stop sent — waiting for events…\n")

        # Drain events until summary.ready (or timeout)
        while True:
            try:
                raw = await asyncio.wait_for(ws.recv(), timeout=120.0)
            except TimeoutError:
                print("  timed out waiting for events")
                break
            msg = json.loads(raw)
            t = msg.get("type", "?")
            if t == "transcript.delta":
                print(f"  [asr] {msg.get('text', '')}")
            elif t == "cue.new":
                print(f"  [cue:{msg.get('cue_type','')}] {msg.get('title','')} — {msg.get('body','')[:80]}")
            elif t == "summary.ready":
                print(f"\n  [summary] {msg.get('title','')}")
                print(f"  {msg.get('prose','')}")
                for item in msg.get("action_items", []):
                    print(f"    - {item}")
                break
            elif t == "session.stopped":
                print("  session stopped — waiting for summary…")
            else:
                print(f"  [{t}]")

    print("\nDone.")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Replay a fixture transcript through ACIS.")
    parser.add_argument("transcript", help="Path to fixture transcript.txt")
    parser.add_argument("--url", default="ws://192.168.204.102:8765",
                        help="WS server URL (default: ws://192.168.204.102:8765)")
    parser.add_argument("--lines", type=int, default=0,
                        help="Only use first N lines (0 = all)")
    parser.add_argument("--delay", type=float, default=0.05,
                        help="Seconds between text lines (default: 0.05)")
    args = parser.parse_args()

    utterances = parse_transcript(args.transcript)
    if args.lines:
        utterances = utterances[:args.lines]

    title = open(args.transcript).readline().strip()
    session_name = title.split(" - ")[0] if " - " in title else title

    print(f"Fixture: {args.transcript}")
    print(f"Session: {session_name}")
    print(f"Lines:   {len(utterances)}")

    asyncio.run(replay(args.url, session_name, utterances, delay=args.delay))


if __name__ == "__main__":
    main()
